repo_url: https://github.com/csia-pme/csia-pme
repo_name: csia-pme/csia-pme
site_name: CSIA-PME
site_author: CSIA-PME contributors
site_url: https://csia-pme.github.io/csia-pme/
site_description: >-
  Documentation website for the CSIA-PME project.
copyright: Copyright &copy; 2022 - 2023 CSIA-PME
nav:
  - Home:
      - index.md
      - Tutorials: tutorials/index.md
      - How-to guides: how-to-guides/index.md
      - Reference: reference/index.md
      - Explanations: explanations/index.md
  - Tutorials:
      - tutorials/index.md
      - Getting started: tutorials/getting-started.md
      - Implement a service: tutorials/implement-service.md
  - How-to guides:
      - how-to-guides/index.md
      - How to add DVC to a service: how-to-guides/how-to-add-dvc-to-a-service.md
      - How to create a GitHub Secret: how-to-guides/how-to-create-a-github-secret.md
      - How to set expiration time on bucket files with MinIO: how-to-guides/how-to-set-expiration-time-on-bucket-files-with-minio.md
      - How to use Material for MkDocs: how-to-guides/how-to-use-material-for-mkdocs.md
  - Reference:
      - reference/index.md
      - Team: reference/team.md
      - Engine: reference/engine.md
      - Service: reference/service.md
      - Pipeline: reference/pipeline.md
      - Webapp: reference/webapp.md
      - ae-ano-detection service: reference/ae-ano-detection.md
      - average-shade service: reference/average-shade.md
      - digit-recognition service: reference/digit-recognition.md
      - face-analyzer service: reference/face-analyzer.md
      - face-detection service: reference/face-detection.md
      - image-sam service: reference/image-sam.md
  - Explanations:
      - explanations/index.md
      - About this documentation: explanations/about-this-documentation.md
      - About DVC: explanations/about-dvc.md
      - About envsubst: explanations/about-envsubst.md
      - About GitHub: explanations/about-github.md
      - About GitHub Actions: explanations/about-github-actions.md
      - About GitHub Secrets: explanations/about-github-secrets.md
      - About HEIA-FR: explanations/about-heia-fr.md
      - About Kubernetes: explanations/about-kubernetes.md
      - About Material for MkDocs: explanations/about-material-for-mkdocs.md
      - About minikube: explanations/about-minikube.md
      - About MinIO: explanations/about-minio.md
      - About yq: explanations/about-yq.md
  - Glossary:
      - glossary.md
edit_uri: blob/main/docs/
theme:
  language: en
  logo: assets/logo.png
  name: material
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - content.code.annotate
    - content.code.copy
    - content.action.edit
    - content.action.view
    - navigation.indexes
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - navigation.footer
    - search.suggest
    - search.highlight
    - toc.follow
plugins:
  - minify:
      minify_html: true
  - search
  - social
  - tags
  - git-revision-date-localized:
      type: datetime
      fallback_to_build_date: true
  - glightbox
extra:
  social:
    - icon: material/earth
      link: https://swiss-ai-center.ch
      name: Swiss AI Center
    - icon: material/github
      link: https://github.com/csia-pme/csia-pme
      name: CSIA-PME on GitHub
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
      base_path: ["docs"]
      auto_append:
        - glossary.md
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - tables
  - toc:
      permalink: true
extra_css:
  - stylesheets/extra.css
extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
  - javascripts/mathjax.js
  - javascripts/tablesort.js
