apiVersion: apps/v1
kind: StatefulSet
metadata:
  # This name uniquely identifies the stateful set
  name: engine-stateful
  labels:
    app: engine
spec:
  serviceName: engine
  replicas: 1
  selector:
    matchLabels:
      app: engine
  template:
    metadata:
      labels:
        app: engine
    spec:
      containers:
        - name: engine
          image: ghcr.io/csia-pme/csia-pme-engine:latest
          # If you build the image locally, change the next line to `imagePullPolicy: Never` - there is no need to pull the image
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8000
          env:
            - name: CHECK_SERVICES_AVAILABILITY_INTERVAL
              value: "30"
          envFrom:
            - configMapRef:
                name: engine-config
