apiVersion: v1
kind: ConfigMap
metadata:
  name: digit-recognition-config
  labels:
    app: digit-recognition
data:
  ENVIRONMENT: development
  LOG_LEVEL: debug
  ENGINE_URLS: '["http://core-engine-service:8080"]'
  SERVICE_URL: http://digit-recognition-service:8484
