apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: image-crop-ingress
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "16m"
    nginx.org/client-max-body-size: "16m"
spec:
  rules:
    - host: image-crop-csia-pme.kube.isc.heia-fr.ch
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: image-crop-service
                port:
                  number: 80
  tls:
    - hosts:
        - image-crop-csia-pme.kube.isc.heia-fr.ch
