apiVersion: apps/v1
kind: StatefulSet
metadata:
  # This name uniquely identifies the stateful set
  name: average-shade-stateful
  labels:
    app: average-shade
spec:
  serviceName: average-shade
  replicas: 1
  selector:
    matchLabels:
      app: average-shade
  template:
    metadata:
      labels:
        app: average-shade
    spec:
      containers:
      - name: average-shade
        image: ghcr.io/swiss-ai-center/core-engine-average-shade:latest
        # If you build the image locally, change the next line to `imagePullPolicy: Never` - there is no need to pull the image
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 80
        env:
        - name: MAX_TASKS
          value: "50"
        - name: ENGINE_ANNOUNCE_RETRIES
          value: "5"
        - name: ENGINE_ANNOUNCE_RETRY_DELAY
          value: "3"
        envFrom:
          - configMapRef:
              name: average-shade-config
