# Documentation: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstepsuses
name: ae-ano-detection_workflow
run-name: ae-ano-detection workflow

# Allow one concurrent deployment
concurrency:
  group: "ae-ano-detection"
  cancel-in-progress: true

on:
  push:
    paths:
      - .github/actions/build-and-push-docker-image-to-github/action.yml
      - .github/actions/execute-command-on-kubernetes-cluster/action.yml
      - .github/actions/run-ml-experiment-with-dvc/action.yml
      - .github/actions/test-python-app/action.yml
      - .github/workflows/ae-ano-detection.yml
      - common-code/**/*
      - services/ae-ano-detection/model_creation/**/*
      - services/ae-ano-detection/model_serving/**/*

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  run-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Run ML experiment with DVC
        uses: ./.github/actions/run-ml-experiment-with-dvc
        with:
          ml-experiment-path: ./services/ae-ano-detection/model_creation
          aws-access-key-id: ${{ secrets.DIGIT_RECOGNITION_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.DIGIT_RECOGNITION_AWS_SECRET_ACCESS_KEY }}

      - name: Move the model to model_serving directory
        shell: bash
        run: mv ./services/ae-ano-detection/model_creation/model/ae_model.h5 ./services/ae-ano-detection/model_serving/ae_model.h5

      - name: Lint Python app
        uses: ./.github/actions/lint-python-app
        with:
          python-app-path: ./services/ae-ano-detection/model_serving

      - name: Test Python app
        uses: ./.github/actions/test-python-app
        with:
          python-app-path: ./services/ae-ano-detection/model_serving

      - name: Build and push Docker image to GitHub
        id: build-and-push-docker-image-to-github
        # Only run on main
        if: github.ref == 'refs/heads/main'
        uses: ./.github/actions/build-and-push-docker-image-to-github
        with:
          docker-registry-username: ${{ github.actor }}
          docker-registry-password: ${{ secrets.GITHUB_TOKEN }}
          docker-image-name: ${{ github.repository }}-ae-ano-detection
          docker-image-context: ./services/ae-ano-detection/model_serving

      - name: Prepare configuration files
        # Only run on main
#        if: github.ref == 'refs/heads/main'
        shell: bash
        working-directory: services/ae-ano-detection/model_serving/kubernetes
        env:
          ENVIRONMENT: production
          LOG_LEVEL: info
          ENGINE_URL: https://engine-csia-pme.kube.isc.heia-fr.ch
          SERVICE_URL: https://ae-ano-detection-csia-pme.kube.isc.heia-fr.ch
        run: |
          # Set ae-ano-detection version
          docker_image_tags=(${{ steps.build-and-push-docker-image-to-github.outputs.docker-image-tags }})
          docker_image_sha_tag="${docker_image_tags[1]}"
          yq ".spec.template.spec.containers[0].image = \"$docker_image_sha_tag\"" ae-ano-detection.stateful.yml > new-ae-ano-detection.stateful.yml && mv new-ae-ano-detection.stateful.yml ae-ano-detection.stateful.yml

          # Set ae-ano-detection configuration
          yq '.data = (.data | to_entries | map({"key": .key, "value": "${" + .key + "}"}) | from_entries)' ae-ano-detection.config-map.yml | envsubst > new-ae-ano-detection.config-map.yml && mv new-ae-ano-detection.config-map.yml ae-ano-detection.config-map.yml

      - name: Deploy ae-ano-detection on the Kubernetes cluster
        # Only run on main
#        if: github.ref == 'refs/heads/main'
        uses: ./.github/actions/execute-command-on-kubernetes-cluster
        with:
          kube-config: ${{ secrets.KUBE_CONFIG }}
          kube-namespace: csia-pme-prod
          kubectl-context: ./services/ae-ano-detection/model_serving/kubernetes
          kubectl-args: |
            apply \
              -f ae-ano-detection.config-map.yml \
              -f ae-ano-detection.stateful.yml \
              -f ae-ano-detection.service.yml \
              -f ae-ano-detection.ingress.yml
