# Documentation: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstepsuses
name: engine-workflow
run-name: engine workflow

# Allow one concurrent deployment
concurrency:
  group: "engine"
  cancel-in-progress: true

on:
  push:
    branches:
      - main
    paths:
      - .github/actions/build-and-push-docker-image-to-github/action.yml
      - .github/actions/execute-command-on-kubernetes-cluster/action.yml
      - .github/actions/lint-python-app/action.yml
      - .github/actions/test-python-app/action.yml
      - .github/workflows/engine.yml
      - common-code/**/*
      - engine/**/*

  pull_request:
    paths:
      - .github/actions/build-and-push-docker-image-to-github/action.yml
      - .github/actions/execute-command-on-kubernetes-cluster/action.yml
      - .github/actions/lint-python-app/action.yml
      - .github/actions/test-python-app/action.yml
      - .github/workflows/engine.yml
      - common-code/**/*
      - engine/**/*

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Lint Python app
        uses: ./.github/actions/lint-python-app
        with:
          python-app-path: ./engine

  test:
    needs: review
    runs-on: ubuntu-latest
    permissions:
      # Gives the action the necessary permissions for publishing new
      # comments in pull requests.
      pull-requests: write
      # Gives the action the necessary permissions for pushing data to the
      # python-coverage-comment-action branch, and for editing existing
      # comments (to avoid publishing multiple comments in the same PR)
      contents: write
    defaults:
      run:
        working-directory: ./engine
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Test Python app
        uses: ./.github/actions/test-python-app
        with:
          python-app-path: ./engine
          token: ${{ secrets.GITHUB_TOKEN }}

  release:
    needs: test
    runs-on: ubuntu-latest
    # Only run on main
    if: success() && github.ref == 'refs/heads/main'
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Build and push Docker image to GitHub
        id: build-and-push-docker-image-to-github
        uses: ./.github/actions/build-and-push-docker-image-to-github
        with:
          docker-registry-username: ${{ github.actor }}
          docker-registry-password: ${{ secrets.GITHUB_TOKEN }}
          docker-image-name: ${{ github.repository }}-engine
          docker-image-context: ./engine
    outputs:
      docker-image-tags: ${{ steps.build-and-push-docker-image-to-github.outputs.docker-image-tags }}

  deploy:
    needs: release
    runs-on: ubuntu-latest
    # Only run on main
    if: success() && github.ref == 'refs/heads/main'
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Prepare configuration files
        shell: bash
        working-directory: engine/kubernetes
        env:
          HOST: https://engine-csia-pme.kube.isc.heia-fr.ch
          ENVIRONMENT: production
          LOG_LEVEL: info
          # TODO: Enable database URL
          DATABASE_URL: ${{ secrets.ENGINE_DATABASE_URL }}
          DATABASE_CONNECT_ARGS: '"{}"'
          # DATABASE_URL: sqlite:///engine.db
          # DATABASE_CONNECT_ARGS: '"{ \"check_same_thread\": \"False\" }"'
          S3_ACCESS_KEY_ID: ${{ secrets.ENGINE_S3_ACCESS_KEY_ID }}
          S3_SECRET_ACCESS_KEY: ${{ secrets.ENGINE_S3_SECRET_ACCESS_KEY }}
          S3_HOST: ${{ secrets.ENGINE_S3_HOST }}
          S3_REGION: ${{ secrets.ENGINE_S3_REGION }}
          S3_BUCKET: ${{ secrets.ENGINE_S3_BUCKET }}
        run: |
          # Set Engine version
          docker_image_tags=(${{ needs.release.outputs.docker-image-tags }})
          docker_image_sha_tag="${docker_image_tags[1]}"
          yq ".spec.template.spec.containers[0].image = \"$docker_image_sha_tag\"" engine.stateful.yml > new-engine.stateful.yml && mv new-engine.stateful.yml engine.stateful.yml

          # Set Engine configuration
          yq '.data = (.data | to_entries | map({"key": .key, "value": "${" + .key + "}"}) | from_entries)' engine.config-map.yml | envsubst > new-engine.config-map.yml && mv new-engine.config-map.yml engine.config-map.yml

      - name: Deploy Engine on the Kubernetes cluster
        # Only run on main
        if: github.ref == 'refs/heads/main'
        uses: ./.github/actions/execute-command-on-kubernetes-cluster
        with:
          kube-config: ${{ secrets.KUBE_CONFIG }}
          kube-namespace: csia-pme-prod
          kubectl-context: ./engine/kubernetes
          kubectl-args: |
            apply \
              -f engine.config-map.yml \
              -f engine.stateful.yml \
              -f engine.service.yml \
              -f engine.ingress.yml
