# Documentation: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstepsuses
name: image-sam_workflow
run-name: image-sam workflow

# Allow one concurrent deployment
concurrency:
  group: "image-sam"
  cancel-in-progress: true

on:
  push:
    branches:
      - main
      - prod
    paths:
      - .github/actions/build-and-push-docker-image-to-github/action.yml
      - .github/actions/execute-command-on-kubernetes-cluster/action.yml
      - .github/actions/lint-python-app/action.yml
      - .github/actions/test-python-app/action.yml
      - .github/workflows/image-sam.yml
      - common-code/**/*
      - services/image-sam/**/*

  pull_request:
    paths:
      - .github/actions/build-and-push-docker-image-to-github/action.yml
      - .github/actions/execute-command-on-kubernetes-cluster/action.yml
      - .github/actions/lint-python-app/action.yml
      - .github/actions/test-python-app/action.yml
      - .github/workflows/image-sam.yml
      - common-code/**/*
      - services/image-sam/**/*

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Lint Python app
        uses: ./.github/actions/lint-python-app
        with:
          python-app-path: ./services/image-sam

  test:
    needs: review
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Test Python app
        uses: ./.github/actions/test-python-app
        with:
          python-app-path: ./services/image-sam
          token: ${{ secrets.GITHUB_TOKEN }}

  release:
    needs: test
    runs-on: ubuntu-latest
    # Only run on main
    if: success() && github.ref == 'refs/heads/main'
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Build and push Docker image to GitHub
        id: build-and-push-docker-image-to-github
        uses: ./.github/actions/build-and-push-docker-image-to-github
        with:
          docker-registry-username: ${{ github.actor }}
          docker-registry-password: ${{ secrets.GITHUB_TOKEN }}
          docker-image-name: ${{ github.repository }}-image-sam
          docker-image-context: ./services/image-sam
    outputs:
      docker-image-tags: ${{ steps.build-and-push-docker-image-to-github.outputs.docker-image-tags }}

  deploy:
    needs: release
    runs-on: ubuntu-latest
    # Only run on main
    if: success() && github.ref == 'refs/heads/main'
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Prepare configuration files
        shell: bash
        working-directory: services/image-sam/kubernetes
        env:
          ENVIRONMENT: production
          LOG_LEVEL: info
          ENGINE_URLS: "'[\"https://engine-csia-pme.kube.isc.heia-fr.ch\"]'"
          SERVICE_URL: https://image-sam-csia-pme.kube.isc.heia-fr.ch
        run: |
          # Set image-sam version
          docker_image_tags=(${{ needs.release.outputs.docker-image-tags }})
          docker_image_sha_tag="${docker_image_tags[1]}"
          yq ".spec.template.spec.containers[0].image = \"$docker_image_sha_tag\"" image-sam.stateful.yml > new-image-sam.stateful.yml && mv new-image-sam.stateful.yml image-sam.stateful.yml

          # Set image-sam configuration (ConfigMap)
          yq '.data = (.data | to_entries | map({"key": .key, "value": "${" + .key + "}"}) | from_entries)' image-sam.config-map.yml | envsubst > new-image-sam.config-map.yml && mv new-image-sam.config-map.yml image-sam.config-map.yml

          # Set image-sam configuration (Ingress)
          yq ".spec.rules[0].host = \"$SERVICE_URL\"" image-sam.ingress.yml > image-sam.ingress.yml
          yq ".spec.tls[0].hosts[0] = \"$SERVICE_URL\"" image-sam.ingress.yml > image-sam.ingress.yml

      - name: Deploy image-sam on the Kubernetes cluster
        uses: ./.github/actions/execute-command-on-kubernetes-cluster
        with:
          kube-config: ${{ secrets.KUBE_CONFIG }}
          kube-namespace: csia-pme-prod
          kubectl-context: ./services/image-sam/kubernetes
          kubectl-args: |
            apply \
              -f image-sam.config-map.yml \
              -f image-sam.stateful.yml \
              -f image-sam.service.yml \
              -f image-sam.ingress.yml

  deploy-prod:
    needs: release
    runs-on: ubuntu-latest
    # Only run on prod
    if: success() && github.ref == 'refs/heads/prod'
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Prepare configuration files
        shell: bash
        working-directory: services/image-sam/kubernetes
        env:
          ENVIRONMENT: production
          LOG_LEVEL: info
          ENGINE_URLS: "'[\"https://engine-csia-pme.kube.isc.heia-fr.ch\"]'"
          SERVICE_URL: https://image-sam-csia-pme.kube.isc.heia-fr.ch
        run: |
          # Set image-sam version
          docker_image_tags=(${{ needs.release.outputs.docker-image-tags }})
          docker_image_sha_tag="${docker_image_tags[1]}"
          yq ".spec.template.spec.containers[0].image = \"$docker_image_sha_tag\"" image-sam.stateful.yml > new-image-sam.stateful.yml && mv new-image-sam.stateful.yml image-sam.stateful.yml

          # Set image-sam configuration (ConfigMap)
          yq '.data = (.data | to_entries | map({"key": .key, "value": "${" + .key + "}"}) | from_entries)' image-sam.config-map.yml | envsubst > new-image-sam.config-map.yml && mv new-image-sam.config-map.yml image-sam.config-map.yml

          # Set image-sam configuration (Ingress)
          yq ".spec.rules[0].host = \"$SERVICE_URL\"" image-sam.ingress.yml > image-sam.ingress.yml
          yq ".spec.tls[0].hosts[0] = \"$SERVICE_URL\"" image-sam.ingress.yml > image-sam.ingress.yml

      - name: Deploy image-sam on the Kubernetes cluster
        uses: ./.github/actions/execute-command-on-kubernetes-cluster
        with:
          kube-config: ${{ secrets.KUBE_CONFIG }}
          kube-namespace: csia-pme-prod
          kubectl-context: ./services/image-sam/kubernetes
          kubectl-args: |
            apply \
              -f image-sam.config-map.yml \
              -f image-sam.stateful.yml \
              -f image-sam.service.yml \
              -f image-sam.ingress.yml
